export const countries = [
    { name: 'Oman', code: 'OM', dial_code: '+968', flag: '🇴🇲' },
    { name: 'Saudi Arabia', code: 'SA', dial_code: '+966', flag: '🇸🇦' },
    { name: 'United Arab Emirates', code: 'AE', dial_code: '+971', flag: '🇦🇪' },
    { name: 'Kuwait', code: 'KW', dial_code: '+965', flag: '🇰🇼' },
    { name: 'Qatar', code: 'QA', dial_code: '+974', flag: '🇶🇦' },
    { name: 'Bahrain', code: 'BH', dial_code: '+973', flag: '🇧🇭' },
    { name: 'Afghanistan', code: 'AF', dial_code: '+93', flag: '🇦🇫' },
    { name: 'Albania', code: 'AL', dial_code: '+355', flag: '🇦🇱' },
    { name: 'Algeria', code: 'DZ', dial_code: '+213', flag: '🇩🇿' },
    { name: 'Andorra', code: 'AD', dial_code: '+376', flag: '🇦🇩' },
    { name: 'Angola', code: 'AO', dial_code: '+244', flag: '🇦🇴' },
    { name: 'Argentina', code: 'AR', dial_code: '+54', flag: '🇦🇷' },
    { name: 'Armenia', code: 'AM', dial_code: '+374', flag: '🇦🇲' },
    { name: 'Australia', code: 'AU', dial_code: '+61', flag: '🇦🇺' },
    { name: 'Austria', code: 'AT', dial_code: '+43', flag: '🇦🇹' },
    { name: 'Azerbaijan', code: 'AZ', dial_code: '+994', flag: '🇦🇿' },
    { name: 'Bangladesh', code: 'BD', dial_code: '+880', flag: '🇧🇩' },
    { name: 'Belgium', code: 'BE', dial_code: '+32', flag: '🇧🇪' },
    { name: 'Brazil', code: 'BR', dial_code: '+55', flag: '🇧🇷' },
    { name: 'Canada', code: 'CA', dial_code: '+1', flag: '🇨🇦' },
    { name: 'China', code: 'CN', dial_code: '+86', flag: '🇨🇳' },
    { name: 'Egypt', code: 'EG', dial_code: '+20', flag: '🇪🇬' },
    { name: 'France', code: 'FR', dial_code: '+33', flag: '🇫🇷' },
    { name: 'Germany', code: 'DE', dial_code: '+49', flag: '🇩🇪' },
    { name: 'India', code: 'IN', dial_code: '+91', flag: '🇮🇳' },
    { name: 'Indonesia', code: 'ID', dial_code: '+62', flag: '🇮🇩' },
    { name: 'Iraq', code: 'IQ', dial_code: '+964', flag: '🇮🇶' },
    { name: 'Italy', code: 'IT', dial_code: '+39', flag: '🇮🇹' },
    { name: 'Japan', code: 'JP', dial_code: '+81', flag: '🇯🇵' },
    { name: 'Jordan', code: 'JO', dial_code: '+962', flag: '🇯🇴' },
    { name: 'Lebanon', code: 'LB', dial_code: '+961', flag: '🇱🇧' },
    { name: 'Malaysia', code: 'MY', dial_code: '+60', flag: '🇲🇾' },
    { name: 'Mexico', code: 'MX', dial_code: '+52', flag: '🇲🇽' },
    { name: 'Morocco', code: 'MA', dial_code: '+212', flag: '🇲🇦' },
    { name: 'Netherlands', code: 'NL', dial_code: '+31', flag: '🇳🇱' },
    { name: 'New Zealand', code: 'NZ', dial_code: '+64', flag: '🇳🇿' },
    { name: 'Pakistan', code: 'PK', dial_code: '+92', flag: '🇵🇰' },
    { name: 'Philippines', code: 'PH', dial_code: '+63', flag: '🇵🇭' },
    { name: 'Russia', code: 'RU', dial_code: '+7', flag: '🇷🇺' },
    { name: 'Singapore', code: 'SG', dial_code: '+65', flag: '🇸🇬' },
    { name: 'South Africa', code: 'ZA', dial_code: '+27', flag: '🇿🇦' },
    { name: 'South Korea', code: 'KR', dial_code: '+82', flag: '🇰🇷' },
    { name: 'Spain', code: 'ES', dial_code: '+34', flag: '🇪🇸' },
    { name: 'Sri Lanka', code: 'LK', dial_code: '+94', flag: '🇱🇰' },
    { name: 'Switzerland', code: 'CH', dial_code: '+41', flag: '🇨🇭' },
    { name: 'Thailand', code: 'TH', dial_code: '+66', flag: '🇹🇭' },
    { name: 'Turkey', code: 'TR', dial_code: '+90', flag: '🇹🇷' },
    { name: 'United Kingdom', code: 'GB', dial_code: '+44', flag: '🇬🇧' },
    { name: 'United States', code: 'US', dial_code: '+1', flag: '🇺🇸' },
    { name: 'Vietnam', code: 'VN', dial_code: '+84', flag: '🇻🇳' }
]

export const getCountryName = (code: string) => {
    const country = countries.find(c => c.code === code)
    return country ? country.name : code
}
